blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using nuclei-templates
    url: https://github.com/projectdiscovery/fuzzing-templates/discussions/categories/q-a
    about: Ask a question or request support for using fuzzing-templates

  - name: Share idea / feature to discuss for nuclei-templates
    url: https://github.com/projectdiscovery/fuzzing-templates/discussions/categories/ideas
    about: Share idea / feature to discuss for fuzzing-templates

  - name: Connect with PD Team & Community (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team & Community for direct communication